steps:
  - command: |
      echo "Test"
      sleep 10
      echo "Done"
    label: "tmp_test"
  - command: |
      .buildkite/pipeline.sh | buildkite-agent pipeline upload
    label: :pipeline: Upload
  - wait
  - command: "echo \"Done\""
    label: Run other operations
